### ISSUE TITLE
left side usb port cannot work

### ISSUE THREAD

**Issue by whongx** [ayufan-pine64/linux-build#4]
Hi, the left side usb port does not work on 0.4.0 & 0.4.1 release but it works on 0.3.5 release. I tested on pinebook using xenial-pinebook-bspkernel-0.3.5-40.img.xz, xenial-mate-pinebook-bspkernel-0.4.0-44.img.xz and xenial-mate-pinebook-bspkernel-0.4.1-46.img.xz image files.

**Comment by ThomasKaiser** [comment]
Please try `echo usb_host >/sys/devices/soc.0/usbc0.5/otg_role` and start to reference the ports accordingly :)

**Comment by whongx** [comment]
@ThomasKaiser It works!! Thanks!! :)

**Comment by ayufan** [comment]
Resolved here: https://github.com/ayufan-pine64/boot-tools/commit/37f21caf4b058873d607fba84686cc00a742ab51

**Comment by whongx** [comment]
@ayufan Noted! Thanks!! :)

**Comment by ThomasKaiser** [comment]
Doesn't fix it for me:

    root@pinebook:~# grep otg_mode /boot/uEnv.txt 
    # otg_mode=device or host or otg
    # otg_mode=host
    root@pinebook:~# cat /sys/devices/soc.0/usbc0.5/otg_role
    usb_device
